### PR TITLE
Removing the identity migration cs file, since the initial migration …

### PR DESCRIPTION
**Pull request by btormino**
…also merges it.  PLEASE SOMEONE MAKE SURE IT WORKS FOR THEM TOO!

### CODE REVIEW

**Review by gebbia — COMMENTED** [review]
Ok so I forked it and tested it out that way, there were some issues but now I am unsure if those were existing issues.  Please have someone else review it as well. The project does build though.

**Comment by brigid-book** [comment]
Not working. Two different files are trying to create the table "weatherstations". One is 20230123092832_UserInterestMigration and the other is 20230116193726_initial_migration

**Comment by btormino** [comment]
Okay, so Brigid, you were the one who was having problems to begin with with the original.  Now, it's happening with another completely different migration file.  What you described in your original issue posted was similar, yes?

I never had the problem of it doubling tables in SQL. Maybe it's something on your end?  I'm not sure...

**Comment by brigid-book** [comment]
There are literally 2 migrations attempting to create the same table. I gave the details of the migrations and the table names above; you can check those 2 files if you don't believe me.

**Comment by btormino** [comment]
I read everything. I saw everything. I'm saying that if no one else if having the issue, it's probably on your machine. This branch took out one of the two files that you had mentioned in your issue. Now, you've said this branch doesn't work because there's a NEW problem with two other migration files.  Which leads me to think there is something going on in your environment that's making you have the issue that others don't seem to be having. My comment was never about not believing you, it was trying to asses the next step of the problem solving process.

**Comment by brigid-book** [comment]
You can see that one of the files is creating the table "weatherstations" and then another file is too. That is here in these files online. Two migrations are trying to create the same table, and we both agree on that, right? And we know that trying to create the same table twice causes an error. That means the error is here and not on my computer.

**Comment by brigid-book** [comment]
And the new error isn't necessarily new. It might have been there before and just didn't get that far because it ran into the other error first.

**Pull request closed without merging**
